In [1]:
import numpy as np
arr=np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[0:5]=100

In [7]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [8]:
arr=np.arange(0,11)

In [9]:
slicearr=arr[0:5]

In [10]:
slicearr

array([0, 1, 2, 3, 4])

In [11]:
slicearr[:]=99

In [12]:
slicearr

array([99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [14]:
arr2d=np.array([[5,10,20],[25,30,40],[45,50,60]])

In [15]:
arr2d

array([[ 5, 10, 20],
       [25, 30, 40],
       [45, 50, 60]])

In [16]:
arr2d.shape

(3, 3)

In [19]:
arr2d[1][2]

40

In [21]:
arr2d[1,2]

40

In [24]:
arr2d[:2,1:]

array([[10, 20],
       [30, 40]])

In [25]:
arr2d

array([[ 5, 10, 20],
       [25, 30, 40],
       [45, 50, 60]])

In [26]:
arr=np.arange(1,11)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
bool=arr > 4

In [30]:
bool

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
arr[bool]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])