In [1]:
print("The first Data Science Library is Numpy")

The first Data Science Library is Numpy


In [2]:
import numpy as np

In [4]:
mylist=[1,2,3,4,5]

In [5]:
type(mylist)

list

In [7]:
myarr=np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(5,6,2)

array([[[0.01413331, 0.62260833],
        [0.1797474 , 0.70698081],
        [0.69184176, 0.74559505],
        [0.03014958, 0.99921798],
        [0.50947333, 0.89148122],
        [0.48970743, 0.22649096]],

       [[0.68091167, 0.74483882],
        [0.53387577, 0.13069881],
        [0.74818872, 0.00753344],
        [0.22935095, 0.36591534],
        [0.86931184, 0.18312735],
        [0.14799805, 0.15324308]],

       [[0.14089285, 0.41879992],
        [0.26478517, 0.09519449],
        [0.72186147, 0.24907136],
        [0.89143893, 0.21502148],
        [0.16478727, 0.78505412],
        [0.35238649, 0.92836589]],

       [[0.61064238, 0.17527396],
        [0.02874066, 0.43944964],
        [0.58445282, 0.0555548 ],
        [0.06765662, 0.88160356],
        [0.08507985, 0.62733979],
        [0.62035238, 0.83703948]],

       [[0.39085909, 0.23360998],
        [0.91551202, 0.2360464 ],
        [0.01298156, 0.63502877],
        [0.3847695 , 0.08057723],
        [0.7403273 , 0.1691361 ],
      

In [32]:
np.random.randn(7)

array([-0.68797738,  1.16214834,  1.2733157 ,  2.10094177, -0.86602787,
       -0.2881165 ,  0.31326683])

In [33]:
np.random.randint(0,101,20)

array([72, 49, 26,  0, 95, 41, 55, 44,  5, 81, 85,  4, 95, 27,  3, 88, 33,
        7, 38, 30])

In [34]:
np.random.randint(0,10,(2,5))

array([[8, 1, 5, 4, 3],
       [2, 7, 5, 8, 1]])

In [40]:
np.random.seed(40)
np.random.rand(4)

array([0.40768703, 0.05536604, 0.78853488, 0.28730518])

In [38]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [41]:
arr=np.arange(0,25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
rarr=np.random.randint(0,101,10)

In [46]:
rarr

array([12, 71, 19, 31, 74, 55, 83, 59, 91, 73])

In [47]:
rarr.max()

91

In [48]:
rarr.min()

12

In [49]:
rarr.argmax()

8

In [51]:
rarr.dtype

dtype('int32')

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
arr.shape

(25,)

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
arr.reshape(1,25) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [56]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [57]:
print("Searching and Indexing")

Searching and Indexing


In [58]:
arr=np.arange(0,11)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[8]

8